export class Accessoire {

    acces_id: number ;
	acces_code: Number;
    acces_codeapporteur: Number ;
    acces_codebranche: Number ;
    acces_codecategorie: Number ;
    acces_codeproduit: Number ;
    acces_codegarantie: Number ;
    acces_interv1: Number ;
    acces_interv2: Number ;
    acces_compagnie1: Number ;
    acces_apporteur1: Number ;
    acces_interv3: Number ;
    acces_interv4: Number ;
    acces_compagnie2: Number ;
    acces_apporteur2: Number ;
    acces_interv5: Number ;
    acces_interv6: Number ;
    acces_compagnie3: Number ;
    acces_apporteur3: Number ;
    acces_interv7: Number ;
    acces_interv8: Number ;
    acces_compagnie4: Number ;
    acces_apporteur4: Number ;
    acces_interv9: Number ;
    acces_interv10: Number ;
    acces_compagnie5: Number ;
    acces_apporteur5: Number ;
    acces_interv11: Number ;
    acces_interv12: Number ;
    acces_compagnie6: Number ;
    acces_apporteur6: Number ;
    acces_interv13: Number ;
    acces_interv14: Number ;
    acces_compagnie7: Number ;
    acces_apporteur7: Number ;
    acces_datepriseffet: Date ;
    acces_datefineffet: Date ;
}