export class Facture {
fact_numacte: Number;
fact_datefacture;
fact_numeropolice: Number;
fact_numeroacte: Number; 
fact_numeroquittance: Number;
fact_marche: String;
fact_numerosouscripteurcontrat: Number;
fact_numeoracheteur: Number;
fact_numeroassure: Number;
fact_numerobeneficiaire: Number;
fact_objetfacture: String;
fact_montantprimenet: Number;
fact_montantaccescompagnie: Number;
fact_montantaccesapporteur: Number;
fact_montanttaxe: Number;
fact_montantarrondi: Number;
fact_commissionapporteur: Number;
fact_montantttc: Number;
fact_numerobranche: Number;
fact_numerocategorie: Number;
fact_dateeffetcontrat: Date;
fact_dateecheancecontrat: Date;
fact_capitalassure: Number;
fact_capitalsmp: Number;
fact_capitallci: Number;
fact_datecomptabilisation: Date;
fact_codeutilisateur: String;
fact_datemodification: Date;
fact_etatfacture: String;
fact_codeannulation: String;
fact_dateannulation: Date;
fact_anciennumerofacture: String;
active: Number;
}